Repository objectiv/objectiv-analytics, pull requests merged in 2022-11, with the labels that each got.

#1424 Bach - Add Athena to readmes
  bach/CONTRIBUTING.md
  bach/README.md
Labels: Area: Bach, Area: Docs, Component: Athena

#1427 Bach: NULL UUIDs fix when doing `to_pandas`
  bach/bach/series/series_uuid.py
  bach/tests/functional/bach/test_series_uuid.py
Labels: Type: Bug, Area: Bach

#1428 Update Objectiv Up inthebox image
  README.md
Labels: Type: Under the Hood

#1360 Bach: make ffill propagation on windows possible
  bach/bach/dataframe.py
  bach/bach/operations/value_propagation.py
  bach/tests/functional/bach/test_df_fillna.py
Labels: Area: Bach

#1421 Better error message in df constructor if index does not match series index
  bach/bach/dataframe.py
Labels: Area: Bach

#1432 Add BQ check in the notebooks for temp tables
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  notebooks/marketing-analytics.ipynb
  notebooks/model-hub-demo-notebook.ipynb
Labels: Area: Modeling

#1433 Fix date in open-taxonomy notebook
  bach/docs/source/example-notebooks/open-taxonomy.rst
  notebooks/open-taxonomy-how-to.ipynb
Labels: Area: Modeling

#1431 Bach improve column name escaping
  bach/bach/merge.py
  bach/bach/utils.py
  bach/tests/functional/bach/test_revert_merge.py
  bach/tests/unit/bach/test_series.py
  bach/tests/unit/bach/test_utils.py
Labels: Type: Enhancement, Area: Bach, Component: BigQuery, Component: Athena

#1423 Bach simplify `from_pandas()` by making `convert_objects=True` by default
  bach/bach/dataframe.py
  bach/bach/operations/cut.py
  bach/bach/quantile.py
  bach/bach/series/series_datetime.py
  bach/bach/series/series_json.py
  bach/docs/source/bach/usage.rst
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/user-intent.rst
  bach/tests/functional/bach/test_cut.py
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_df.py
  bach/tests/functional/bach/test_df_append.py
  bach/tests/functional/bach/test_df_describe.py
  bach/tests/functional/bach/test_df_drop_duplicates.py
  bach/tests/functional/bach/test_df_dropna.py
  bach/tests/functional/bach/test_df_fillna.py
  bach/tests/functional/bach/test_df_get_dummies.py
  bach/tests/functional/bach/test_df_indexing.py
  bach/tests/functional/bach/test_df_merge.py
  bach/tests/functional/bach/test_df_sort_values.py
  bach/tests/functional/bach/test_df_window.py
  bach/tests/functional/bach/test_series.py
  bach/tests/functional/bach/test_series_date.py
  bach/tests/functional/bach/test_series_describe.py
  bach/tests/functional/bach/test_series_drop_duplicates.py
  bach/tests/functional/bach/test_series_json.py
  bach/tests/functional/bach/test_series_multi_level.py
  bach/tests/functional/bach/test_series_numeric.py
  bach/tests/functional/bach/test_series_time.py
  bach/tests/functional/bach/test_series_timedelta.py
  modelhub/tests_modelhub/data_and_utils/utils.py
  modelhub/tests_modelhub/functional/conftest.py
  modelhub/tests_modelhub/functional/modelhub/test_pipelines_extracted_contexts.py
  modelhub/tests_modelhub/functional/modelhub/test_pipelines_identity_resolution.py
  modelhub/tests_modelhub/functional/modelhub/test_pipelines_sessionized_data.py
  notebooks/basic-user-intent.ipynb
  notebooks/marketing-analytics.ipynb
Labels: Area: Bach

#1436 Fix missing user IDs for Snowplow Collector
  backend/objectiv_backend/snowplow/snowplow_helper.py
Labels: Area: Tracking

#1439 Fix marketing-analytics notebook Docusaurus run
  bach/docs/source/example-notebooks/marketing-analytics.rst
Labels: Area: Docs

#1440 [Bach/MH] Bach and Modelhub version to v0.0.27
  bach/bach/__init__.py
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  modelhub/modelhub/__init__.py
  modelhub/setup.cfg
Labels: Type: Under the Hood

#1425 Fix config for fields to hash
  backend/objectiv_backend/common/config.py
Labels: Area: Tracking

#1412 Checklock: Save outputs and update history in AWS Bucket
  modelhub/tests_modelhub/checklock_holmes/checklock-holmes.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/checklock_kernel/kernel.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/checklock_kernel/manager.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/checklock_nb_client/notebook_client.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/checklock_nb_client/notebook_engine.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/errors/exceptions.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/kernel_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/nb_checker_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/nb_checker.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/__init__.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/handler.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/utils.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/settings.py
  modelhub/tests_modelhub/checklock_holmes/mypy.ini
Labels: Area: Modeling

#1413 Checklock: Compare outputs based on stored history
  modelhub/tests_modelhub/checklock_holmes/.gitignore
  modelhub/tests_modelhub/checklock_holmes/checklock-holmes.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/nb_checker_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/output_history_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/handler.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/utils.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/reporting/utils.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/utils/constants.py
Labels: Area: Modeling

#1415 Checklock: Saves and reads history locally
  modelhub/tests_modelhub/checklock_holmes/.gitignore
  modelhub/tests_modelhub/checklock_holmes/checklock-holmes.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/checklock_kernel/kernel.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/nb_checker_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/handler.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/settings.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/utils/helpers.py
Labels: Area: Modeling

#1443 Notebook tweaks and fix conversion event in marketing analytics notebook
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  notebooks/marketing-analytics.ipynb
  notebooks/model-hub-demo-notebook.ipynb
Labels: Area: Up

#1448 Switch deprecated 'sklearn' requirement to 'scikit-learn'
  modelhub/setup.cfg
Labels: Area: Modeling, Type: Under the Hood

#1449 Clarification about Postgres support
  bach/CONTRIBUTING.md
  bach/README.md
Labels: Area: Bach, Type: Under the Hood

#1444 Checklock: Compare outputs from local dir
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/models/nb_checker_models.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/output_history/handler.py
Labels: Area: Modeling, Type: Under the Hood

#1434 Bach strftime support `%V`
  bach/bach/series/series_datetime.py
  bach/bach/series/utils/datetime_formats.py
  bach/tests/functional/bach/test_series_date.py
  bach/tests/unit/bach/test_series_utils_datetime_formats.py
Labels: Type: Enhancement, Area: Bach

#1450 Enable tables for Sphinx Docusaurus builder
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  modelhub/modelhub/modelhub.py
Labels: Area: Docs

#1446 Enable typevars for Sphinx Docusaurus builder
  bach/docs/requirements.txt
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  bach/docs/source/conf.py
  modelhub/modelhub/modelhub.py
Labels: Area: Docs
