Repository objectiv/objectiv-analytics, pull requests merged in 2022-08, with the labels that each got.

#1091 Angular 9.1.13 compatibility
  tracker/.changeset/angry-glasses-talk.md
  tracker/.changeset/hip-kids-flash.md
  tracker/.changeset/mean-impalas-sing.md
  tracker/.changeset/pre.json
  tracker/.changeset/silly-tools-check.md
  tracker/.changeset/wet-knives-joke.md
  tracker/core/developer-tools/package.json
  tracker/core/react/package.json
  tracker/core/schema/package.json
  tracker/core/testing-tools/package.json
  tracker/core/tracker/package.json
  tracker/core/utilities/package.json
  tracker/plugins/application-context/package.json
  tracker/plugins/http-context/package.json
  tracker/plugins/identity-context/package.json
  tracker/plugins/locale-context/package.json
  tracker/plugins/path-context-from-url/package.json
  tracker/plugins/react-navigation/package.json
  tracker/plugins/react-router-tracked-components/package.json
  tracker/plugins/root-location-context-from-url/package.json
  tracker/queues/local-storage/package.json
  tracker/trackers/angular/package.json
  tracker/trackers/angular/src/index.ts
  tracker/trackers/browser/package.json
  tracker/trackers/react-native/package.json
  tracker/trackers/react/package.json
  tracker/transports/debug/package.json
  tracker/transports/fetch/package.json
  tracker/transports/xhr/package.json
  tracker/yarn.lock
Labels: Type: Bug, Area: Tracking

#1088 Tracking SDKs v0.0.24: TS Schema interfaces, Angular SDK compatibility tweaks
  tracker/core/developer-tools/package.json
  tracker/core/react/package.json
  tracker/core/schema/package.json
  tracker/core/schema/src/generated/abstracts.ts
  tracker/core/schema/src/generated/discriminators.ts
  tracker/core/schema/src/generated/events.ts
  tracker/core/schema/src/generated/global_contexts.ts
  tracker/core/schema/src/generated/index.ts
  tracker/core/schema/src/generated/location_contexts.ts
  tracker/core/schema/src/index.d.ts
  tracker/core/schema/src/index.ts
  tracker/core/schema/src/static.ts
  tracker/core/testing-tools/package.json
  tracker/core/tracker/package.json
  tracker/core/utilities/package.json
  tracker/core/utilities/src/generateLanguageCodes.js
  tracker/core/utilities/src/generateSchema.js
  tracker/package.json
  tracker/plugins/application-context/package.json
  tracker/plugins/http-context/package.json
  tracker/plugins/identity-context/package.json
  tracker/plugins/locale-context/package.json
  tracker/plugins/path-context-from-url/package.json
  tracker/plugins/react-navigation/package.json
  tracker/plugins/react-router-tracked-components/package.json
  tracker/plugins/root-location-context-from-url/package.json
  tracker/queues/local-storage/package.json
  tracker/trackers/angular/package.json
  tracker/trackers/angular/src/index.ts
  tracker/trackers/browser/package.json
  tracker/trackers/react-native/package.json
  tracker/trackers/react/package.json
  tracker/transports/debug/package.json
  tracker/transports/fetch/package.json
  tracker/transports/xhr/package.json
  tracker/yarn.lock
Labels: Type: Bug, Type: Enhancement, Area: Tracking, Type: Under the Hood

#1092 Cleanup test data functions in test_data_and_utils.py
  bach/README.md
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_df_from.py
Labels: Area: Bach, Type: Under the Hood, Component: BigQuery

#1094 Fix SQL output test in explore-data notebook
  bach/docs/source/example-notebooks/explore-data.rst
Labels: Area: Docs

#1115 Move check_groupby to modelhub.utils
  modelhub/modelhub/aggregate.py
  modelhub/modelhub/util.py
Labels: Area: Modeling

#1116 Bach Support boolean, integer, and float for Athena
  bach/bach/series/series_boolean.py
  bach/bach/series/series_numeric.py
  bach/tests/functional/bach/test_series_boolean.py
  bach/tests/functional/bach/test_series_float.py
  bach/tests/functional/bach/test_series_int.py
  bach/tests/functional/bach/test_series_numeric.py
Labels: Area: Bach, Component: Athena

#1125 Add last step filter in funnel discovery
  modelhub/modelhub/models/funnel_discovery.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_funnel_discovery.py
  notebooks/funnel-discovery.ipynb
Labels: Area: Modeling

#1127 Stateless tracked input components
  tracker/trackers/react/src/index.ts
  tracker/trackers/react/src/trackedContexts/TrackedInputContext.tsx
  tracker/trackers/react/src/trackedElements/TrackedInputRadio.tsx
  tracker/trackers/react/tests/TrackedInputContext.test.tsx
  tracker/trackers/react/tests/TrackedInputRadio.test.tsx
Labels: Area: Tracking, Type: Story

#1124 Bach: SeriesString.str.upper and SeriesString.str.lower
  bach/bach/series/series_string.py
  bach/tests/functional/bach/test_series_string.py
Labels: Area: Bach

#1126 Add start_from_end parameter in navigation paths
  modelhub/modelhub/models/funnel_discovery.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_funnel_discovery.py
Labels: Area: Modeling

#1129 Make multi-query json tests single-query
  bach/tests/functional/bach/test_series_json.py
Labels: Area: Bach, Type: Under the Hood

#1137 FunnelDiscovery class docs
  bach/docs/source/open-model-hub/index.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.get_navigation_paths.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.plot_sankey_diagram.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.rst
  bach/docs/source/open-model-hub/models/funnels/index.rst
  bach/docs/source/open-model-hub/models/index.rst
  modelhub/modelhub/models/funnel_discovery.py
Labels: Area: Modeling

#1128 Funnel discovery release
  bach/bach/dataframe.py
  bach/bach/series/series_boolean.py
  bach/bach/series/series_numeric.py
  bach/bach/series/series_string.py
  bach/bach/series/series_uuid.py
  bach/docs/Makefile
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  bach/docs/source/bach/api-reference/Series/String/index.rst
  bach/docs/source/example-notebooks/feature-importance.rst
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/example-notebooks/index.rst
  bach/docs/source/example-notebooks/logistic-regression.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/example-notebooks/open-taxonomy.rst
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-4th-step.png
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-marketing-4th-step.png
  bach/docs/source/index.rst
  bach/docs/source/open-model-hub/index.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.get_navigation_paths.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.plot_sankey_diagram.rst
  bach/docs/source/open-model-hub/models/funnels/FunnelDiscovery/modelhub.FunnelDiscovery.rst
  bach/docs/source/open-model-hub/models/funnels/index.rst
  bach/docs/source/open-model-hub/models/index.rst
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_series_boolean.py
  bach/tests/functional/bach/test_series_float.py
  bach/tests/functional/bach/test_series_int.py
  bach/tests/functional/bach/test_series_json.py
  bach/tests/functional/bach/test_series_numeric.py
  bach/tests/functional/bach/test_series_string.py
  bach/tests/functional/bach/test_series_uuid.py
  modelhub/modelhub/modelhub.py
  modelhub/modelhub/models/funnel_discovery.py
  notebooks/explore-your-data.ipynb
  notebooks/funnel-discovery.ipynb
Labels: Area: Demo

#1118 Funnel Discovery
  bach/bach/dataframe.py
  bach/docs/Makefile
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  bach/docs/source/bach/api-reference/Series/String/index.rst
  bach/docs/source/example-notebooks/feature-importance.rst
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/example-notebooks/index.rst
  bach/docs/source/example-notebooks/logistic-regression.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/example-notebooks/open-taxonomy.rst
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-4th-step.png
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-marketing-4th-step.png
  bach/docs/source/index.rst
  bach/docs/source/open-model-hub/index.rst
  bach/docs/source/open-model-hub/models/funnels/index.rst
  bach/docs/source/open-model-hub/models/index.rst
  modelhub/modelhub/__init__.py
  modelhub/modelhub/aggregate.py
  modelhub/modelhub/modelhub.py
  modelhub/modelhub/models/__init__.py
  modelhub/modelhub/models/funnel_discovery.py
  modelhub/mypy.ini
  modelhub/setup.cfg
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_funnel_discovery.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_navigation_paths.py
  notebooks/explore-your-data.ipynb
  notebooks/funnel-discovery.ipynb
Labels: Area: Modeling

#1130 Bach: Athena base Series `setitem` test
  bach/bach/series/series_boolean.py
  bach/bach/series/series_numeric.py
  bach/bach/series/series_string.py
  bach/bach/series/series_uuid.py
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_df_setitem.py
Labels: Area: Bach, Type: Under the Hood, Component: Athena

#1139 bump version to v0.0.18
  bach/bach/__init__.py
  modelhub/modelhub/__init__.py
  modelhub/setup.cfg
Labels: Area: Modeling, Area: Bach, Type: Under the Hood

#986 Bach: POC graphing SQLModels
  bach/bach/display_formats/__init__.py
  bach/bach/display_formats/graph_display.py
  bach/bach/display_formats/markdown_display.py
  bach/mypy.ini
  bach/setup.cfg
  bach/tests/unit/bach/test_display_formats.py
Labels: Area: Bach

#1089 Bach: Simulate NULLS FIRST and NULLS LAST for BigQuery in window functions
  bach/bach/dataframe.py
  bach/bach/indexing.py
  bach/bach/operations/value_propagation.py
  bach/bach/partitioning.py
  bach/bach/quantile.py
  bach/bach/series/series_multi_level.py
  bach/bach/series/series_string.py
  bach/tests/functional/bach/test_df_window.py
  bach/tests/functional/bach/test_series_string.py
  bach/tests/unit/bach/test_series_window_functions.py
Labels: Area: Bach, Component: BigQuery

#1102 [Checklock] Extend Papermill
  modelhub/tests_modelhub/checklock_holmes/checklock-holmes.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/nb_checker.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/utils/constants.py
  modelhub/tests_modelhub/checklock_holmes/mypy.ini
  modelhub/tests_modelhub/checklock_holmes/requirements.txt
Labels: Type: Under the Hood

#1104 Checklock: Running NB checks asynchronously
  modelhub/tests_modelhub/checklock_holmes/checklock-holmes.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/nb_checker.py
  modelhub/tests_modelhub/checklock_holmes/mypy.ini
  modelhub/tests_modelhub/checklock_holmes/requirements.txt
Labels: Type: Under the Hood

#1138 Support SeriesJson on Athena
  bach/bach/series/array_operations/flattening.py
  bach/bach/series/series_json.py
  bach/tests/functional/bach/test_df_setitem.py
  bach/tests/functional/bach/test_series_json.py
Labels: Area: Bach, Component: Athena

#1144 Replace PNGs in the readme for vectors
  README.md
Labels: Type: Under the Hood

#1150 Update categories of model hub operations available
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/open-model-hub/index.rst
  bach/docs/source/open-model-hub/models/index.rst
Labels: Area: Docs

#1156 React SDK: Name attribute support for radios and checkboxes
  tracker/trackers/react/src/trackedContexts/TrackedInputContext/TrackedInputContextRadio.tsx
  tracker/trackers/react/src/trackedElements/TrackedInputCheckbox.tsx
  tracker/trackers/react/src/trackedElements/TrackedInputRadio.tsx
  tracker/trackers/react/tests/TrackedInputCheckbox.test.tsx
  tracker/trackers/react/tests/TrackedInputRadio.test.tsx
Labels: Type: Enhancement, Area: Tracking

#1145 Remove Bach from notebook requirements
  notebooks/requirements.txt
Labels: Type: Under the Hood

#1146 Checklock: cell tagging
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/nb_checker.py
  modelhub/tests_modelhub/checklock_holmes/checklock_holmes/utils/cell_tags.py
Labels: Type: Under the Hood, Area: Demo

#1090 Bach: Raise exception when window partitioning has no order by columns.
  bach/bach/dataframe.py
  bach/bach/series/series.py
  bach/tests/functional/bach/test_df_window.py
Labels: Area: Bach

#1153 Bach: strict other dtypes in binary ops
  bach/bach/series/series.py
  bach/bach/series/series_boolean.py
  bach/bach/series/series_datetime.py
  bach/bach/series/series_json.py
  bach/bach/series/series_numeric.py
  bach/bach/series/series_string.py
  bach/tests/functional/bach/test_series_json.py
Labels: Area: Bach, Component: Athena

#1162 Modelhub: Refactoring of FunnelDiscovery model
  modelhub/modelhub/models/funnel_discovery.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_funnel_discovery.py
Labels: Type: Enhancement, Area: Modeling

#1151 Bach: SeriesAbstractDateTime support more literals in datetime series
  bach/bach/series/series.py
  bach/bach/series/series_boolean.py
  bach/bach/series/series_datetime.py
  bach/bach/series/series_dict.py
  bach/bach/series/series_json.py
  bach/bach/series/series_list.py
  bach/bach/series/series_numeric.py
  bach/bach/series/series_uuid.py
  bach/tests/unit/bach/test_series_date.py
  bach/tests/unit/bach/test_series_time.py
  bach/tests/unit/bach/test_series_timestamp.py
Labels: Component: Athena

#1167 Update sankey plots in the docs
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-4th-step.png
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-marketing-4th-step.png
Labels: Area: Modeling

#1160 Refactor FunnelDiscovery.plot_sankey_diagram
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-4th-step.png
  bach/docs/source/img/docs/example-notebooks/funnel-discovery-plot-sankey-marketing-4th-step.png
  modelhub/modelhub/models/funnel_discovery.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_funnel_discovery.py
Labels: Area: Modeling

#1171 Align outputs of the code in Funnel Discovery docs
  bach/docs/source/example-notebooks/funnel-discovery.rst
Labels: Area: Docs

#1173 ModelHub: Limit retrieved elements from array subquery
  modelhub/modelhub/series/series_objectiv.py
Labels: Type: Bug, Area: Modeling

#1174 Add comment about BigQuery in funnel-discovery notebook
  notebooks/funnel-discovery.ipynb
Labels: Area: Modeling

#1172 bump version to v0.0.19
  bach/bach/__init__.py
  modelhub/modelhub/__init__.py
  modelhub/setup.cfg
Labels: Type: Under the Hood

#1152 Bach: Support Athena Timestamp
  bach/bach/series/series.py
  bach/bach/series/series_boolean.py
  bach/bach/series/series_datetime.py
  bach/bach/series/series_json.py
  bach/bach/series/series_numeric.py
  bach/bach/series/series_string.py
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_series_json.py
  bach/tests/functional/bach/test_series_timestamp.py
Labels: Area: Bach, Component: Athena

#1134 Bach: Add test for complex type to json conversion on BQ, and implement.
  bach/bach/series/series_json.py
  bach/tests/functional/bach/test_series_json.py
Labels: Area: Bach

#1155 Bach: support athena date
  bach/bach/series/series_datetime.py
  bach/tests/functional/bach/test_series_date.py
  bach/tests/unit/bach/test_series_date.py
Labels: Area: Bach, Component: Athena

#1098 Flatten contexts in SP/BQ
  backend/objectiv_backend/common/config.py
  backend/objectiv_backend/end_points/collector.py
  backend/objectiv_backend/end_points/extra_output.py
  backend/objectiv_backend/snowplow/generate_iglu_schema.py
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractGlobalContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractLocationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ApplicationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ContentContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/CookieIdContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ExpandableContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/HttpContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/IdentityContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/InputContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/InputValueContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/LinkContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/LocaleContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/MarketingContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/MediaPlayerContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/NavigationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/OverlayContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/PathContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/PressableContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/RootLocationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/SessionContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv/location_stack/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv/taxonomy/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/snowplow_helper.py
  backend/objectiv_backend/tools/pg_to_sp.py
  backend/tests/collector/test_snowplow.py
  backend/tests/schema/test_schema.py
Labels: Area: Tracking

#1169 Add Marketing Analytics notebook
  bach/bach/dataframe.py
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/feature-engineering.rst
  bach/docs/source/example-notebooks/feature-importance.rst
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/example-notebooks/index.rst
  bach/docs/source/example-notebooks/logistic-regression.rst
  bach/docs/source/example-notebooks/machine-learning.rst
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/example-notebooks/open-taxonomy.rst
  bach/docs/source/example-notebooks/product-analytics.rst
  bach/docs/source/example-notebooks/user-intent.rst
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-conversion-rate-from-marketing.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-conversion-rate-overall.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-conversions-overall.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-funnel-all.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-funnel-converted.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-number-conversions-from-marketing.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-users-from-marketing.png
  bach/docs/source/img/docs/example-notebooks/marketing-analytics-users-per-source-campaign.png
  bach/docs/source/img/docs/example-notebooks/product-analytics-retention-matrix.png
  notebooks/basic-product-analytics.ipynb
  notebooks/marketing-analytics.ipynb
Labels: Area: Demo

#1178 Fix iglu schema
  backend/objectiv_backend/snowplow/generate_iglu_schema.py
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractGlobalContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/AbstractLocationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ApplicationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ContentContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/CookieIdContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/ExpandableContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/HttpContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/IdentityContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/InputContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/InputValueContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/LinkContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/LocaleContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/MarketingContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/MediaPlayerContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/NavigationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/OverlayContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/PathContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/PressableContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/RootLocationContext/jsonschema/1-0-0
  backend/objectiv_backend/snowplow/iglu/io.objectiv.context/SessionContext/jsonschema/1-0-0
Labels: Area: Tracking

#1180 Allow an event time to be slightly in the future
  backend/objectiv_backend/schema/validate_events.py
Labels: Area: Tracking

#1183 Add BI export how-to to notebooks
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/product-analytics.rst
  bach/docs/source/example-notebooks/user-intent.rst
  notebooks/basic-product-analytics.ipynb
  notebooks/basic-user-intent.ipynb
  notebooks/explore-your-data.ipynb
  notebooks/funnel-discovery.ipynb
  notebooks/marketing-analytics.ipynb
  notebooks/model-hub-demo-notebook.ipynb
Labels: Area: Demo

#1181 Change data start and end dates in basic-product-analytics
  bach/docs/source/example-notebooks/product-analytics.rst
  bach/docs/source/img/docs/example-notebooks/product-analytics-retention-matrix.png
  notebooks/basic-product-analytics.ipynb
Labels: Area: Modeling

#1186 Set explicit start and end date for notebooks with doctests
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/funnel-discovery.rst
  bach/docs/source/example-notebooks/marketing-analytics.rst
  bach/docs/source/example-notebooks/product-analytics.rst
  notebooks/basic-product-analytics.ipynb
  notebooks/explore-your-data.ipynb
  notebooks/funnel-discovery.ipynb
  notebooks/marketing-analytics.ipynb
Labels: Area: Demo

#1185 add metabase container back
  docker-compose.yaml
  notebooks/docker/2_metabase_data.sql
  notebooks/docker/Dockerfile
Labels: Area: Demo, Area: Visualization

#1187 Tweak supported data stores
  bach/docs/source/bach/data-stores.rst
Labels: Area: Docs

#1196 Tweak notebooks readme
  notebooks/README.md
Labels: Type: Under the Hood

#1197 Add funnels to open model hub readme
  modelhub/README.md
Labels: Type: Under the Hood

#1200 Fix doctests for `view_sql` format update
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/product-analytics.rst
Labels: Area: Docs
