Repository objectiv/objectiv-analytics, pull requests merged in 2022-06, with the labels that each got.

#789 ModelHub: Unit Tests for BasePipeline, ExtractedContextsPipeline, SessionizedDataPipeline and utils
  .github/workflows/modelhub_tests.yml
  modelhub/tests_modelhub/unit/__init__.py
  modelhub/tests_modelhub/unit/modelhub/__init__.py
  modelhub/tests_modelhub/unit/modelhub/test_stack_base_pipeline.py
  modelhub/tests_modelhub/unit/modelhub/test_stack_extracted_contexts.py
  modelhub/tests_modelhub/unit/modelhub/test_stack_sessionized_data.py
  modelhub/tests_modelhub/unit/modelhub/test_stack_util.py
Labels: Area: Modeling, Component: BigQuery

#792 ModelHub: Functional Tests for ExtractedContextsPipeline and SessionizedDataPipeline
  modelhub/tests_modelhub/functional/modelhub/test_stack_extracted_contexts.py
  modelhub/tests_modelhub/functional/modelhub/test_stack_sessionized_data.py
Labels: Area: Modeling, Component: BigQuery

#822 Bugfix: Consistent and configurable id normalization in React Tracker components
  tracker/plugins/react-router-tracked-components/src/TrackedLink.tsx
  tracker/plugins/react-router-tracked-components/src/TrackedNavLink.tsx
  tracker/trackers/react/src/common/factories/makeIdFromTrackedAnchorProps.tsx
  tracker/trackers/react/src/trackedContexts/TrackedContentContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedExpandableContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedInputContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedMediaPlayerContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedNavigationContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedOverlayContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedPressableContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedRootLocationContext.tsx
  tracker/trackers/react/src/types.ts
  tracker/trackers/react/tests/TrackedAnchor.test.tsx
  tracker/trackers/react/tests/TrackedButton.test.tsx
  tracker/trackers/react/tests/TrackedContentContext.test.tsx
  tracker/trackers/react/tests/TrackedDiv.test.tsx
  tracker/trackers/react/tests/TrackedExpandableContext.test.tsx
  tracker/trackers/react/tests/TrackedFooter.test.tsx
  tracker/trackers/react/tests/TrackedHeader.test.tsx
  tracker/trackers/react/tests/TrackedInput.test.tsx
  tracker/trackers/react/tests/TrackedInputContext.test.tsx
  tracker/trackers/react/tests/TrackedLinkContext.test.tsx
  tracker/trackers/react/tests/TrackedMain.test.tsx
  tracker/trackers/react/tests/TrackedMediaPlayerContext.test.tsx
  tracker/trackers/react/tests/TrackedNav.test.tsx
  tracker/trackers/react/tests/TrackedNavigationContext.test.tsx
  tracker/trackers/react/tests/TrackedOverlayContext.test.tsx
  tracker/trackers/react/tests/TrackedPressableContext.test.tsx
  tracker/trackers/react/tests/TrackedRootLocationContext.test.tsx
  tracker/trackers/react/tests/TrackedSection.test.tsx
  tracker/trackers/react/tests/makeIdFromTrackedAnchorProps.test.ts
Labels: Type: Enhancement, Area: Tracking, Type: Breaking Change

#808 Workflow to add opened issues/PRs to Development board
  .github/workflows/add_issues_to_project.yml
Labels: Type: Under the Hood

#828 Add `dependabot[bot]` to CLA workflow allowlist
  .github/workflows/cla.yml
Labels: Type: Under the Hood

#830 [ModelHub]: Fix import for NamedTuple
  modelhub/modelhub/stack/extracted_contexts.py
Labels: Type: Bug, Area: Modeling

#839 Support recent NPM
  tracker/.gitignore
  tracker/.yarn/plugins/@objectiv/plugin-engines-check.js
  tracker/.yarnrc.yml
  tracker/CONTRIBUTING.md
  tracker/Makefile
  tracker/core/developer-tools/package.json
  tracker/core/react/package.json
  tracker/core/schema/package.json
  tracker/core/tracker/package.json
  tracker/package.json
  tracker/plugins/http-context/package.json
  tracker/plugins/path-context-from-url/package.json
  tracker/plugins/react-navigation/package.json
  tracker/plugins/react-router-tracked-components/package.json
  tracker/plugins/root-location-context-from-url/package.json
  tracker/queues/local-storage/package.json
  tracker/trackers/angular/package.json
  tracker/trackers/browser/package.json
  tracker/trackers/react-native/package.json
  tracker/trackers/react/package.json
  tracker/transports/debug/package.json
  tracker/transports/fetch/package.json
  tracker/transports/xhr/package.json
  tracker/yarn.lock
Labels: Area: Tracking, Type: Under the Hood

#832 [Bach]: `NULLS LAST` by default in Order By Clause
  bach/bach/dataframe.py
  bach/bach/partitioning.py
  bach/tests/functional/bach/test_cut.py
  bach/tests/functional/bach/test_df_fillna.py
  bach/tests/functional/bach/test_df_merge.py
  bach/tests/functional/bach/test_df_sort_values.py
Labels: Area: Bach

#835 [BQ: Bach] Convert Rollup test for BigQuery
  bach/tests/functional/bach/test_df_groupby.py
Labels: Area: Bach, Component: BigQuery

#797 Bach: Support C-Standard Date Codes in `DateTimeOperation.sql_format`
  .github/workflows/modelhub_tests.yml
  bach/bach/series/series_datetime.py
  bach/bach/series/utils/__init__.py
  bach/bach/series/utils/datetime_formats.py
  bach/tests/functional/bach/test_series_date.py
  bach/tests/unit/bach/test_series_utils_datetime_formats.py
  modelhub/pytest.ini
Labels: Area: Bach, Component: BigQuery

#842 ModelHub BQ: Use `dt.strftime` instead of `dt.sql_format`
  modelhub/modelhub/modelhub.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_session_duration.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_unique_sessions.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_unique_users.py
  notebooks/basic-product-analytics.ipynb
  notebooks/basic-user-intent.ipynb
  notebooks/feature-engineering.ipynb
  notebooks/model-hub-demo-notebook.ipynb
  notebooks/modelhub-logistic-regression.ipynb
Labels: Area: Modeling, Component: BigQuery

#800 ModelHub BQ: Support `Map.is_new_user`
  modelhub/modelhub/map.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub.py
Labels: Area: Modeling, Component: BigQuery

#848 Make plugin lists extendible, instead of replaceable, in all Trackers
  tracker/core/tracker/src/TrackerTransportRetryAttempt.ts
  tracker/trackers/angular/src/AngularTracker.ts
  tracker/trackers/browser/src/BrowserTracker.ts
  tracker/trackers/browser/tests/BrowserTracker.test.ts
  tracker/trackers/browser/tests/getElementLocationStack.test.ts
  tracker/trackers/react-native/src/ReactNativeTracker.ts
  tracker/trackers/react-native/tests/ReactNativeTracker.test.ts
  tracker/trackers/react/src/ReactTracker.ts
  tracker/trackers/react/tests/ReactTracker.test.ts
Labels: Type: Bug, Area: Tracking, Type: Breaking Change

#849 bump version to 0.0.9
  bach/bach/__init__.py
  modelhub/modelhub/__init__.py
  modelhub/setup.cfg
Labels: Type: Under the Hood

#850 Fix docstring for series-datetime
  bach/bach/series/series_datetime.py
Labels: Type: Bug, Area: Docs

#843 ModelHub BQ: json series globalcontext
  bach/bach/series/series_json.py
  bach/tests/unit/bach/test_series_json.py
  modelhub/modelhub/series/series_objectiv.py
  modelhub/tests_modelhub/functional/modelhub/test_series_objectiv.py
Labels: Area: Modeling, Area: Bach, Component: BigQuery

#831 Bach BQ: Support `fillna` for BigQuery
  bach/bach/dataframe.py
  bach/bach/operations/value_propagation.py
  bach/tests/functional/bach/test_df_fillna.py
Labels: Area: Bach, Component: BigQuery

#866 Migrate date format in example notebooks
  bach/docs/source/example-notebooks/index.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/example-notebooks/product-analytics.rst
  notebooks/basic-product-analytics.ipynb
  notebooks/model-hub-demo-notebook.ipynb
  notebooks/sklearn-example.ipynb
Labels: Area: Docs

#864 Update modeling docs intro
  bach/docs/source/index.rst
Labels: Area: Docs

#863 bump version to v0.0.11
  bach/bach/__init__.py
  modelhub/modelhub/__init__.py
  modelhub/setup.cfg
Labels: Type: Under the Hood

#859 Run modelhub tests on github against BigQuery too
  .github/workflows/bach-tests.yml
  .github/workflows/modelhub_tests.yml
  modelhub/tests_modelhub/conftest.py
Labels: Area: Modeling, Type: Under the Hood, Component: BigQuery

#865 Modelhub run tests in parallel
  .github/workflows/modelhub_tests.yml
  modelhub/Makefile
  modelhub/pytest.ini
  modelhub/requirements-dev.txt
  modelhub/tests_modelhub/conftest.py
  modelhub/tests_modelhub/data_and_utils/utils.py
  modelhub/tests_modelhub/functional/conftest.py
Labels: Area: Modeling, Type: Under the Hood

#856 Bach unittest, convert tests to multi-database
  bach/tests/functional/bach/test_data_and_utils.py
  bach/tests/functional/bach/test_df_scale.py
  bach/tests/functional/bach/test_df_setitem.py
  bach/tests/functional/bach/test_df_sort_index.py
  bach/tests/functional/bach/test_df_stack.py
  bach/tests/functional/bach/test_df_unstack.py
  bach/tests/functional/bach/test_df_variables.py
  bach/tests/functional/bach/test_injection_escaping.py
  bach/tests/functional/bach/test_series.py
  bach/tests/functional/bach/test_series_boolean.py
  bach/tests/functional/bach/test_series_float.py
  bach/tests/functional/bach/test_series_int.py
  bach/tests/functional/bach/test_series_numeric.py
  bach/tests/functional/bach/test_series_string.py
  bach/tests/functional/bach/test_series_timedelta.py
Labels: Area: Bach, Type: Under the Hood, Component: BigQuery

#875 Remove obsolete time format
  modelhub/README.md
Labels: Area: Modeling

#876 Missing description in the doc page
  bach/docs/source/example-notebooks/logistic-regression.rst
Labels: Area: Modeling

#883 Bach BQ: Remove hack from DataFrame.quantile
  bach/bach/dataframe.py
  bach/bach/operations/describe.py
  bach/tests/functional/bach/test_df.py
Labels: Area: Bach, Component: BigQuery

#886 Fix bach README
  bach/README.md
Labels: Area: Bach

#887 Bach BQ: Remove `COALESCE` from `JsonBigQueryAccessorImpl.get_value`
  bach/bach/series/series_json.py
Labels: Area: Bach, Component: BigQuery

#838 ModelHub BQ: Add conversion event
  modelhub/modelhub/map.py
Labels: Area: Modeling, Component: BigQuery

#874 Tracker Developer Tools: Event Recorder
  tracker/core/developer-tools/src/EventRecorder.ts
  tracker/core/developer-tools/src/index.ts
  tracker/core/developer-tools/tests/EventRecorder.test.ts
  tracker/core/react/tests/ObjectivProvider.test.tsx
  tracker/core/react/tests/TrackerProvider.test.tsx
  tracker/core/react/tests/TrackingContextProvider.test.tsx
  tracker/core/tracker/src/EventRecorderInterface.ts
  tracker/core/tracker/src/Tracker.ts
  tracker/core/tracker/src/TrackerDeveloperToolsInterface.ts
  tracker/core/tracker/src/index.ts
  tracker/core/tracker/tests/Tracker.test.ts
  tracker/trackers/browser/tests/BrowserTracker.test.ts
  tracker/trackers/react-native/tests/ReactNativeTracker.test.ts
  tracker/trackers/react/tests/ReactTracker.test.ts
  tracker/trackers/react/tests/withoutDOM.test.ts
Labels: Area: Tracking

#889 Show more results for better demonstration logistic regression
  bach/docs/source/example-notebooks/logistic-regression.rst
  notebooks/model-hub-logistic-regression.ipynb
Labels: Area: Modeling, Area: Demo

#891 Bach BQ: JSON Slicing with dicts
  bach/bach/series/series_json.py
  bach/tests/functional/bach/test_series_json.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub.py
  modelhub/tests_modelhub/functional/modelhub/test_series_objectiv.py
Labels: Area: Bach, Component: BigQuery

#885 Bach BQ: Support `SeriesJson.__ge__` for BigQuery
  bach/bach/series/series_json.py
  bach/tests/functional/bach/test_series_json.py
Labels: Area: Bach, Component: BigQuery

#888 Bach BQ: Remove Nano-precision from aggregated SeriesTimedelta
  bach/bach/series/series_datetime.py
  bach/tests/functional/bach/test_series_timedelta.py
  bach/tests/unit/bach/test_series_timedelta.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_session_duration.py
Labels: Area: Bach, Component: BigQuery

#898 Rename column names in top product features
  modelhub/modelhub/aggregate.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_top_product_features.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_top_product_features_before_conversion.py
Labels: Area: Modeling

#905 Add an 'explore your data' example notebook
  bach/docs/source/example-notebooks/explore-data.rst
  bach/docs/source/example-notebooks/feature-engineering.rst
  bach/docs/source/example-notebooks/feature-importance.rst
  bach/docs/source/example-notebooks/index.rst
  bach/docs/source/example-notebooks/logistic-regression.rst
  bach/docs/source/example-notebooks/modelhub-basics.rst
  bach/docs/source/example-notebooks/open-taxonomy.rst
  notebooks/basic-product-analytics.ipynb
  notebooks/explore-your-data.ipynb
  notebooks/feature-engineering.ipynb
  notebooks/model-hub-demo-notebook.ipynb
  notebooks/model-hub-logistic-regression.ipynb
  notebooks/open-taxonomy-how-to.ipynb
  notebooks/sklearn-example.ipynb
Labels: Area: Demo

#915 Modelhub location stack nice name prep better
  modelhub/modelhub/series/series_objectiv.py
  modelhub/tests_modelhub/data_and_utils/data_json_real.py
  modelhub/tests_modelhub/functional/modelhub/test_series_objectiv.py
Labels: Area: Modeling, Type: Under the Hood

#916 Modelhub location stack nice name
  bach/bach/series/series_json.py
  modelhub/modelhub/series/series_objectiv.py
  modelhub/tests_modelhub/functional/modelhub/test_series_objectiv.py
Labels: Area: Modeling, Component: BigQuery

#900 Deprecate le and ge for json Series
  bach/bach/series/series_json.py
  bach/docs/source/example-notebooks/product-analytics.rst
  bach/tests/functional/bach/test_series_json.py
  modelhub/modelhub/aggregate.py
  notebooks/basic-product-analytics.ipynb
Labels: Area: Bach

#917 Bach fix for `.json[negative index]` and other small improvements
  bach/bach/series/series_json.py
  bach/tests/functional/bach/test_series_json.py
Labels: Type: Bug, Area: Bach, Type: Under the Hood, Component: BigQuery

#920 Simplify _bigquery_filter_keys_of_dicts as discussed
  modelhub/modelhub/series/series_objectiv.py
Labels: Area: Modeling, Type: Under the Hood, Component: BigQuery

#877 Add Retention Matrix model
  bach/docs/source/_ext/sphinx_docusaurus_builder/docusaurus_writer.py
  bach/docs/source/example-notebooks/product-analytics.rst
  bach/docs/source/open-model-hub/models/aggregation/index.rst
  bach/docs/source/open-model-hub/models/index.rst
  modelhub/modelhub/aggregate.py
  modelhub/mypy.ini
  modelhub/requirements.txt
  modelhub/setup.cfg
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_retention_matrix.py
  notebooks/basic-product-analytics.ipynb
Labels: Area: Modeling

#938 Bach BQ: Removed `materialization` when in DataFrame.groupby
  bach/bach/dataframe.py
  bach/bach/partitioning.py
  bach/bach/series/series_multi_level.py
  bach/tests/functional/bach/test_df_getitem.py
  bach/tests/functional/bach/test_df_groupby.py
  modelhub/modelhub/map.py
Labels: Area: Bach, Component: BigQuery

#939 ModelHub BQ: Drop rows with duplicated ids
  bach/bach/dataframe.py
  modelhub/modelhub/stack/extracted_contexts.py
Labels: Area: Bach, Component: BigQuery

#903 ModelHub: Calculate dependent conversion series at once
  modelhub/modelhub/aggregate.py
  modelhub/modelhub/map.py
  modelhub/tests_modelhub/functional/modelhub/test_model_hub_top_product_features_before_conversion.py
Labels: Area: Modeling

#952 Bach: `use materialize(distinct=True)` in Series.unique
  bach/bach/dataframe.py
  bach/bach/series/series.py
  bach/tests/functional/bach/test_series.py
Labels: Area: Bach

#901 Support temporary tables for bigquery
  bach/bach/dataframe.py
  bach/bach/operations/describe.py
  bach/bach/savepoints.py
  bach/sql_models/model.py
  bach/sql_models/sql_generator.py
  bach/tests/functional/bach/test_df_materialize.py
  bach/tests/functional/bach/test_savepoints.py
  bach/tests/functional/sql_models/test_sql_generator_materialization.py
  bach/tests/unit/sql_models/test_sql_generator_materialization.py
Labels: Area: Bach, Component: BigQuery

#953 Bach: SeriesString.str.replace
  bach/bach/series/series_string.py
  bach/tests/functional/bach/test_series_string.py
Labels: Area: Bach

#957 [Modeling: modelhub-logistic-regression] Replace dashes with underscores for series to unstack
  bach/docs/source/example-notebooks/logistic-regression.rst
  notebooks/model-hub-logistic-regression.ipynb
Labels: Area: Modeling

#956 [Modeling: sklearn-example] Replace dashes with underscores for series to unstack
  bach/docs/source/example-notebooks/machine-learning.rst
  notebooks/sklearn-example.ipynb
Labels: Area: Modeling
