Repository objectiv/objectiv-analytics, pull requests merged in 2022-02, with the labels that each got.

#434 CJS support and some bug-fixes
  tracker/core/schema/package.json
  tracker/core/testing-tools/package.json
  tracker/core/tracker/package.json
  tracker/core/tracker/rollup.config.js
  tracker/core/utilities/package.json
  tracker/plugins/path-context-from-url/package.json
  tracker/plugins/path-context-from-url/rollup.config.js
  tracker/plugins/root-location-context-from-url/package.json
  tracker/plugins/root-location-context-from-url/rollup.config.js
  tracker/queues/local-storage/package.json
  tracker/queues/local-storage/rollup.config.js
  tracker/trackers/angular/package.json
  tracker/trackers/angular/src/objectiv-tracker.directive.ts
  tracker/trackers/browser/package.json
  tracker/trackers/browser/rollup.config.js
  tracker/trackers/react/package.json
  tracker/trackers/react/rollup.config.js
  tracker/trackers/react/src/hooks/useOnChange.ts
  tracker/trackers/react/src/trackedElements/TrackedAnchor.tsx
  tracker/trackers/react/tests/TrackedAnchor.test.tsx
  tracker/transports/debug/package.json
  tracker/transports/debug/rollup.config.js
  tracker/transports/fetch/package.json
  tracker/transports/fetch/rollup.config.js
  tracker/transports/xhr/package.json
  tracker/transports/xhr/rollup.config.js
  tracker/tsconfig.json
  tracker/yarn.lock
Labels: Area: Tracking, Type: Story

#448 Tracker: improvements and clean up
  tracker/CONTRIBUTING.md
  tracker/package.json
  tracker/trackers/browser/src/BrowserTracker.ts
  tracker/trackers/browser/tests/BrowserTracker.test.ts
  tracker/trackers/react/src/ReactTracker.ts
  tracker/trackers/react/src/common/factories/makeDefaultPluginsList.ts
  tracker/trackers/react/tests/ReactTracker.test.ts
Labels: Type: Enhancement, Area: Tracking

#466 Browser/Angular Trackers: tweaks and fixes from feedback
  tracker/core/schema/package.json
  tracker/core/testing-tools/package.json
  tracker/core/tracker/package.json
  tracker/core/tracker/src/helpers.ts
  tracker/core/tracker/tests/helpers.test.ts
  tracker/core/utilities/package.json
  tracker/plugins/http-context/package.json
  tracker/plugins/path-context-from-url/package.json
  tracker/plugins/root-location-context-from-url/package.json
  tracker/queues/local-storage/package.json
  tracker/trackers/angular/package.json
  tracker/trackers/angular/src/index.ts
  tracker/trackers/angular/src/objectiv-tracker.directive.ts
  tracker/trackers/angular/src/objectiv-tracker.filter.ts
  tracker/trackers/angular/src/objectiv-tracker.module.ts
  tracker/trackers/browser/package.json
  tracker/trackers/browser/src/common/guards/isClickableContext.ts
  tracker/trackers/browser/src/common/guards/isPressableContext.ts
  tracker/trackers/browser/src/common/guards/isTrackVisibilityAttribute.ts
  tracker/trackers/browser/src/common/parsers/parseTrackVisibility.ts
  tracker/trackers/browser/src/definitions/LocationContext.ts
  tracker/trackers/browser/src/definitions/TrackVisibilityAttribute.ts
  tracker/trackers/browser/src/definitions/TrackVisibilityOptions.ts
  tracker/trackers/browser/src/index.ts
  tracker/trackers/browser/src/locationTaggers/tagLocation.ts
  tracker/trackers/browser/src/mutationObserver/trackNewElement.ts
  tracker/trackers/browser/src/mutationObserver/trackRemovedElement.ts
  tracker/trackers/browser/src/mutationObserver/trackVisibilityHiddenEvent.ts
  tracker/trackers/browser/src/mutationObserver/trackVisibilityVisibleEvent.ts
  tracker/trackers/browser/tests/parsersAndStringifiers.test.ts
  tracker/trackers/browser/tests/tagLocation.test.ts
  tracker/trackers/browser/tests/tagLocationHelpers.test.ts
  tracker/trackers/browser/tests/trackNewElement.test.ts
  tracker/trackers/browser/tests/trackNewElements.test.ts
  tracker/trackers/react/package.json
  tracker/trackers/react/src/common/factories/makeIdFromString.ts
  tracker/trackers/react/src/common/factories/makeTitleFromChildren.ts
  tracker/trackers/react/src/index.ts
  tracker/trackers/react/src/trackedContexts/TrackedLinkContext.tsx
  tracker/trackers/react/src/trackedContexts/TrackedPressableContext.tsx
  tracker/trackers/react/tests/makeIdFromString.test.ts
  tracker/transports/debug/package.json
  tracker/transports/fetch/package.json
  tracker/transports/xhr/package.json
  tracker/yarn.lock
Labels: Type: Enhancement, Area: Tracking

#485 Update License year to 2022
  LICENSE.md
Labels: Status: Ignore for Changelog

#486 Fix link
  CONTRIBUTING.md
Labels: Status: Ignore for Changelog

#377 Add release.yml for auto-generation of changelogs
  .github/release.yml
Labels: Area: Project, Status: Ignore for Changelog
